import "reflect-metadata";
import { promises as fs } from "fs";
import { printSchema } from "graphql/utilities";
import { buildSchema } from "type-graphql";
import schemaOptions from "./schemaOptions";

const header = `
# -----------------------------------------------
# !!! CREATED_AT : ${new Date().toLocaleString()} !!!
# !!! THIS FILE WAS GENERATED BY TYPE-GRAPHQL !!!
# !!!   DO NOT MODIFY THIS FILE BY YOURSELF   !!!
# -----------------------------------------------
`;

(async () => {
  const schema = await buildSchema(schemaOptions);
  const sdl = printSchema(schema);
  await fs.writeFile(
    `${process.cwd()}/__generated__/schema.graphql`,
    `${header}\n${sdl}`,
  );
})();
